### ISSUE TITLE
TODO) 학교, 생년월일 인증추가

### ISSUE THREAD

**Issue by BelBone** [BelBone/EduroAuto#4]
- [x] 처리모듈 제작성공
- [ ] 안정성 테스트, 정상적 처리 테스트
- [x] 실제 앱, 컴퓨터 프로그램에 모듈 추가 및 호환성 검사
- [x] 처리 모듈 인증처리

기존 인증코드와는 별개로 학교와 이름, 생년월일로 인증하는 기능을 베타 버전에 추가하였으며 안정성(질문문항 정상처리, 인증문제)에 대해 면밀히 테스트중입니다.

2020년 06월 14일내에 릴리즈 버전에 포함될 예정입니다.

**Comment by BelBone** [comment]
검증 완료.
